services:
  etcd:
    container_name: milvus-standalone-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_HEARTBEAT_INTERVAL=500
      - ETCD_ELECTION_TIMEOUT=2500
    command: >
      etcd
      --data-dir=/etcd
      --name milvus-etcd
      --initial-advertise-peer-urls http://milvus-standalone-etcd:2380
      --listen-peer-urls http://0.0.0.0:2380
      --advertise-client-urls http://milvus-standalone-etcd:2379
      --listen-client-urls http://0.0.0.0:2379
      --initial-cluster milvus-etcd=http://milvus-standalone-etcd:2380

    volumes:
      - etcd:/etcd
    ports:
      - "2379:2379"
    networks:
      - milvus

  minio:
    container_name: milvus-standalone-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: server /minio_data
    volumes:
      - minio:/minio_data
    ports:
      - "9000:9000"
    networks:
      - milvus

  pulsar:
    container_name: milvus-standalone-pulsar
    image: apachepulsar/pulsar:2.10.2
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8089:8080"
    networks:
      - milvus

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.3.9
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
      - pulsar
    environment:
      - ETCD_ENDPOINTS=http://milvus-standalone-etcd:2379
    restart: always
    networks:
      - milvus

volumes:
  etcd:
  minio:

networks:
  milvus:
